### ISSUE TITLE
Getting a ton of errors thrown in 2015 RC thrown

### ISSUE THREAD

**Issue by bradphelan** [DustinCampbell/CSharpEssentials#12]
![image](https://cloud.githubusercontent.com/assets/17650/7472594/5f12f846-f334-11e4-9b00-68f6df90938d.png)

**Comment by DustinCampbell** [comment]
Hey @bradphelan -- any chance you could share a bit more about this issue? Does this happen with a specific project for you? Or, does it happen for any source?

**Comment by bradphelan** [comment]
I'll look tomorrow. It just dumped about 1000 of these into my quite large
project. I didn't check to see if it affected some subprojects rather than
others. I was just trying to port my project to c# 6 today :)

**Comment by bradphelan** [comment]
I've got about 20 sub projects in my solution. They are all targeting .net 4.6 on the 2015RC release of visual studio. On quick inspection I'd say all of them are throwing the above errors during analysis.

**Comment by dg9ngf** [comment]
I remember I had such exception messages as well. But I can't see them anymore today. Maybe because I've upgraded to 1.0.1.

**Comment by DustinCampbell** [comment]
I think this got fixed with 1.0.1. At least, I haven't seen it since.

**Comment by DustinCampbell** [comment]
I'm going ahead and closing this issue. Looks like it might have been the result of mismatched binaries prior to the 1.0.1 release.
