### ISSUE TITLE
Ignore auto-generated files

### ISSUE THREAD

**Issue by DustinCampbell** [DustinCampbell/CSharpEssentials#14]

**Comment by agrtga** [comment]
Definitely implement ignoring auto-generated files.

**Comment by DustinCampbell** [comment]
This is addressed with PR #18.

**Comment by richardlawley** [comment]
Some auto-generated files are still not being excluded.  Examples I've seen:
* Service References (Reference.cs)
* CSHTML Helper files (e.g. a code file in App_Code containing '@helper' functions.

The Service Reference contains the following comment at the top:

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

I'm not sure if looking for the <auto-generated> tag in a comment would be a better way to find these files?

**Comment by DustinCampbell** [comment]
@richardlawley, let me know if service references are still a problem after this change.

**Comment by richardlawley** [comment]
I'm running 1.0.2 of the extension - unsure whether this has the changes in place, but it still offers suggestion on a Service Reference.

**Comment by DustinCampbell** [comment]
Sorry, I haven't shipped 1.0.3 yet. Will get that out today.

**Comment by DustinCampbell** [comment]
Should be updated now (1.0.4) actually. Let me know if it's working for you.

**Comment by richardlawley** [comment]
Yes, this now looks fine.  Thanks!

**Comment by DustinCampbell** [comment]
Excellent! Glad to hear it's working for you.
