### ISSUE TITLE
CSE0003 doesn't preserve comments

### ISSUE THREAD

**Issue by bmenees** [DustinCampbell/CSharpEssentials#24]
First, thanks for the great analyzers!  I'm really enjoying them.  However, I discovered today that CSE0003 (Consider using an expression-bodied member) loses comments from a member body when it converts it to an expression.  For example, given this method:
```C#
protected virtual bool ReadOptions(string changedOptionId)
{
	// If we're passed a specific option ID, then return false because we can't read it here to tell if it changed.
	// If we're passed null or empty, then return true as if something changed.
	return string.IsNullOrEmpty(changedOptionId);
}
```
CSE0003 turned that into:
```C#
protected virtual bool ReadOptions(string changedOptionId) => string.IsNullOrEmpty(changedOptionId);
```
But I expected something like the following where the comments are preserved:
```C#
// If we're passed a specific option ID, then return false because we can't read it here to tell if it changed.
// If we're passed null or empty, then return true as if something changed.
protected virtual bool ReadOptions(string changedOptionId) => string.IsNullOrEmpty(changedOptionId);
```
I suppose it gets tricky if XML doc comments are also used, so maybe the member body comments should go before or after the arrow operator.  Or maybe CSE0003 shouldn't recommend a change if the member body contains comments.  I'm not sure what would be best, but since this fix can be applied globally to a solution, it would be nice if it didn't lose data in these situations.

Thanks!

**Comment by DustinCampbell** [comment]
Good bug -- thanks!
