### ISSUE TITLE
Addon does not load for VS 2015 Update 1 RC

### ISSUE THREAD

**Issue by AdamDotNet** [DustinCampbell/CSharpEssentials#38]
The error pane shows the warning:

Warning AD1002  Unable to load Analyzer assembly C:<username>\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0\EXTENSIONS\5FFBEBER.SPV\CSharpEssentials.dll: Could not load file or assembly 'CSharpEssentials, Version=1.0.5725.26970, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

I have verified that the file is there, and even built the code using the RC. Not sure what would make this not work anymore, but it makes me very sad!

**Comment by DustinCampbell** [comment]
That is very bizarre. I'm working on this right now.

**Comment by BillWagner** [comment]
@DustinCampbell I'm finding this as well. Also, finding the same situation in an analyzer I'm writing. Any help would be appreciated.

**Comment by DustinCampbell** [comment]
I just took a look and appears that VS 2015 Update 1 RC broke loading of analyzers, but it is fixed for Update 1 RTM. I just verified that C# Essentials works on a VM with VS 2015 RTM + last night's Update 1 build.

**Comment by AdamDotNet** [comment]
Interesting to hear, thanks. Any insider info on when the RTM is? ;)

**Comment by DustinCampbell** [comment]
Posting on a public GitHub repo doesn't really count as "insider info" does it? :smile:

As always, it'll ship when it's done.

**Comment by twenzel** [comment]
@DustinCampbell  Any chance to get this nightly build as well? Have to continue working on my analyzers,

**Comment by AdamDotNet** [comment]
@twenzel I may not be a Microsoft rep like @DustinCampbell, but if your work is hindered by a prerelease version of the software and it's really important to be able to continue working, my advice is to just roll back to RTM until U1 is out as a full release. There are some nice things in U1, like the interactive C# window, but nothing so ground breaking to improve your analyzer work, in my opinion. You know your situation best, however.

**Comment by DustinCampbell** [comment]
Thanks @AdamDotNet -- great answer!

@twenzel, in this morning's keynote for the Connect() event (going on right now!), ScottGu mentioned that Update 1 will be out later this month.

**Comment by twenzel** [comment]
@AdamDotNet Good point. Maybe I'm too goofy, but I'm not able to find a way to roll back the RC. The setup does not provide a way. Is there an instruction to rollback the update 1 RC?

**Comment by AdamDotNet** [comment]
@twenzel The way I handled it was by uninstalling VS and then reinstalling using the RTM media. I chose the web installer.

**Comment by DustinCampbell** [comment]
Just wanted to let folks know that this should be working now that VS 2015 Update 1 RTM has shipped. Let me know if it's not working for you.
