### ISSUE TITLE
CSE0001 shows both as Error and Warning

### ISSUE THREAD

**Issue by tschlarm** [DustinCampbell/CSharpEssentials#40]
Latest update seems to throw CSE0001 as both Warning and error.

![image](https://cloud.githubusercontent.com/assets/5054383/11388346/76f7a62e-92f2-11e5-8ebd-7c880a646e65.png)

Running v1.04 in VS2015 RTM

**Comment by tschlarm** [comment]
Ignore this one, they were different projects. 

However, the settings for the project that was throwing this as an error, had this set as a warning for the Project, Common and All.

**Comment by DustinCampbell** [comment]
Got it. Makes sense.
